CREATE TABLE firma (
    firma_id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firma_name           VARCHAR2(100 CHAR) NOT NULL,
    rechnungs_adresse     VARCHAR2(400 CHAR) NOT NULL,
    kommentar VARCHAR2(2000),
    email VARCHAR2(100 CHAR) NOT NULL
);

CREATE INDEX idx_firma_email ON firma(email);

CREATE TABLE ansprechpartner (
    ansprechpartner_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firma_id          INTEGER NOT NULL,
    vorname           VARCHAR2(100 CHAR) NOT NULL,
    nachname          VARCHAR2(100 CHAR) NOT NULL,
    email             VARCHAR2(100 CHAR) NOT NULL,
    telefon_nummer     VARCHAR2(100 CHAR),
    position_firma     VARCHAR2(100 CHAR),
    CONSTRAINT fk_ansprechpartner_firma FOREIGN KEY (firma_id) REFERENCES firma(firma_id) ON DELETE CASCADE
);

CREATE TABLE teilnehmer_status (
    status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR2(50 CHAR) UNIQUE NOT NULL
);

INSERT INTO teilnehmer_status (status_name) VALUES
('Anmeldung unvollständig'),
('Warten auf Angebotsbestätigung'),
('Angemeldet'),
('Webinar beendet - Warten auf Rechnungsbegleichung'),
('Rechnung beglichen'),
('Teilgenommen'),
('Erinnerung zur Zahlung gesendet'),
('Storniert');
commit;

CREATE TABLE teilnehmer (
    teilnehmer_id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firma_id        INTEGER NOT NULL,
    vorname         VARCHAR2(100 CHAR) NOT NULL,
    nachname        VARCHAR2(100 CHAR) NOT NULL,
    email           VARCHAR2(100 CHAR) NOT NULL UNIQUE,
    status_id        INTEGER DEFAULT 1 NOT NULL,
    CONSTRAINT fk_teilnehmer_firma FOREIGN KEY (firma_id) REFERENCES firma(firma_id) ON DELETE CASCADE,
    CONSTRAINT fk_teilnehmer_status FOREIGN KEY (status_id) REFERENCES teilnehmer_status(status_id) ON DELETE CASCADE
);

CREATE TABLE kurs (
    kurs_id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_name     VARCHAR2(100 CHAR) NOT NULL,
    kurs_typ      VARCHAR2(50 CHAR) CHECK (kurs_typ IN ('Webinar', 'Präsenz')) NOT NULL,
    kurs_ort      VARCHAR2(100 CHAR) NOT NULL,
    kurs_datum_beginn DATE NOT NULL,
    kurs_datum_ende   DATE NOT NULL,
    kommentar VARCHAR2(2000),
    CONSTRAINT kurs_unique UNIQUE (kurs_name, kurs_datum_beginn, kurs_datum_ende)
);

CREATE TABLE kurs_termine (
    termin_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kurs_id        INTEGER NOT NULL,
    datum         DATE NOT NULL,
    uhrzeit_start TIMESTAMP NOT NULL,
    uhrzeit_ende  TIMESTAMP NOT NULL,
    CONSTRAINT fk_kurs_termine FOREIGN KEY (kurs_id) REFERENCES kurs(kurs_id) ON DELETE CASCADE
);
